apiVersion: v1
data:
  .env: |-
    # Database
    DATABASE_URL="postgresql://maas_user:maas_password@localhost:5432/maas_platform"

    # JWT
    JWT_SECRET="your-super-secret-jwt-key-change-this-in-production"
    JWT_EXPIRES_IN="24h"

    # Redis
    REDIS_URL="redis://localhost:6379"

    # API Keys
    API_KEY_SALT_ROUNDS=12

    # Kubernetes
    KUBECONFIG_PATH="/Users/nitzikow/.kube/config"
    KUBE_NAMESPACE="llm"

    # Server
    PORT=3001
    NODE_ENV="development"

    # CORS
    CORS_ORIGIN="http://localhost:3000"
  package.json: |
    {
      "name": "@maas/backend",
      "version": "1.0.0",
      "description": "MaaS Backend API",
      "main": "dist/app.js",
      "scripts": {
        "build": "tsc",
        "start": "node dist/app.js",
        "dev": "ts-node-dev --respawn --transpile-only src/app.ts",
        "test": "jest",
        "lint": "eslint src/**/*.ts",
        "lint:fix": "eslint src/**/*.ts --fix"
      },
      "dependencies": {
        "@kubernetes/client-node": "^0.20.0",
        "axios": "^1.6.0",
        "cors": "^2.8.5",
        "express": "^4.18.2",
        "winston": "^3.11.0"
      },
      "devDependencies": {
        "@types/cors": "^2.8.17",
        "@types/express": "^4.17.21",
        "@types/node": "^20.10.0",
        "ts-node-dev": "^2.0.0",
        "typescript": "^5.3.0"
      }
    }
  tsconfig.json: |-
    {
      "compilerOptions": {
        "target": "ES2020",
        "module": "commonjs",
        "lib": ["ES2020"],
        "outDir": "./dist",
        "rootDir": "./src",
        "strict": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "resolveJsonModule": true,
        "declaration": true,
        "declarationMap": true,
        "sourceMap": true
      },
      "include": ["src/**/*"],
      "exclude": ["node_modules", "dist"]
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: maas-backend-source
  namespace: llm