apiVersion: v1
kind: ServiceAccount
metadata:
  name: maas-backend
  namespace: llm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maas-backend-reader
rules:
- apiGroups: ["kuadrant.io"]
  resources: ["authpolicies", "ratelimitpolicies", "tokenratelimitpolicies"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["get", "list"]
# Prometheus access permissions
- apiGroups: [""]
  resources: ["pods/proxy", "services/proxy", "endpoints/proxy"]
  verbs: ["get", "list", "create"]
- nonResourceURLs: ["/metrics", "/api/v1/query", "/api/v1/query_range", "/api/v1/label/*", "/api/v1/labels", "/api/v1/series"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maas-backend-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: maas-backend-reader
subjects:
- kind: ServiceAccount
  name: maas-backend
  namespace: llm
---
# Additional role binding for OpenShift monitoring
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maas-backend-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: maas-backend
  namespace: llm
---
# System monitoring role for /metrics access
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: maas-backend-system-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:monitoring
subjects:
- kind: ServiceAccount
  name: maas-backend
  namespace: llm
